hyperdog_ros2_pybullet_node:
  ros__parameters:
    # ----------------------------------------------------------
    is_debug: True
    # ----------------------------------------------------------
    num_of_motors: 12
    hip_joint_ids: [0, 3, 6, 9]
    thigh_joint_ids: [1, 4, 7, 10]
    calf_joint_ids: [2, 5, 8, 11]
    # ----------------------------------------------------------
    leg_joint_home_positions: [0, 0, 30]
    # ----------------------------------------------------------
    max_motor_torque: 7.0 # Nm, double
    # ----------------------------------------------------------
    sim_step_time: 0.001     # 
    realtime_sim: True
    sim_plane: "plane.urdf"
    robot_urdf_path: ["hyperdog_robot_description","urdf/hyperdog.urdf"] # [pkg_name, directory_of the_file_in_the_pkg]
    # ----------------------------------------------------------
    # user debug parameters
    motor_torque_limit: [0.0, 20.0]     # Nm, doubles
    robot_height_limit: [80.0, 300.0]   # mm, doubles
    robot_euler_angle_limit: [60.0, 45.0, 50.0]  # [roll(deg), pitch(deg), yaw(yaw)], doubles

